/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BloodDonationManagement.Applicant;

import Main.MainLogin;
import javax.swing.table.DefaultTableModel;
import model.Accept;
import model.Applicant;
import model.Reject;
import model.system;

/**
 *
 * @author arpid
 */
public class BDHiringApplicantPanel extends javax.swing.JFrame {

    /**
     * Creates new form BDHiringApplicantPanel
     */
    system s;
    public BDHiringApplicantPanel(system s) {
        initComponents();
        this.s = s;
        this.setExtendedState(BDHiringApplicantPanel.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BDApplicantSplit = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();
        display1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(display1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(454, Short.MAX_VALUE))
        );

        BDApplicantSplit.setRightComponent(jPanel2);

        jButton1.setText("Job Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Profile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Accepted Applications");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Rejected Applications");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addGap(121, 121, 121)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(home)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        BDApplicantSplit.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BDApplicantSplit)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BDApplicantSplit)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BDHiringApplicantJobSearch sapframe = new BDHiringApplicantJobSearch(s);
        BDApplicantSplit.setRightComponent(sapframe);
        BDHiringApplicantJobSearch.username1.setText(display1.getText());
         for (Applicant epp:s.getApplicantdirectory().getApplicant()){
            if(BDHiringApplicantJobSearch.username1.getText().equals(epp.getUsername())){
                BDHiringApplicantJobSearch.name1.setText(String.valueOf(epp.getName()));
                BDHiringApplicantJobSearch.age1.setText(String.valueOf(epp.getAge()));
                BDHiringApplicantJobSearch.gender1.setSelectedItem(String.valueOf(epp.getGender()));
                BDHiringApplicantJobSearch.id1.setText(String.valueOf(epp.getId()));
                BDHiringApplicantJobSearch.emailid1.setText(String.valueOf(epp.getEmailid()));                
                BDHiringApplicantJobSearch.contact1.setText(String.valueOf(epp.getContact()));                
                BDHiringApplicantJobSearch.qualification1.setText(String.valueOf(epp.getQualification()));
                
            }
         }
                
                
//                BDDonorSlotPanel.username.setText(String.valueOf(selectedep.getUsername()));
               
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        BDHiringApplicantProfile sapframe = new BDHiringApplicantProfile(s);
        BDApplicantSplit.setRightComponent(sapframe);
        
        BDHiringApplicantProfile.username.setText(display1.getText());
        for (Applicant epp:s.getApplicantdirectory().getApplicant()){
            if(BDHiringApplicantProfile.username.getText().equals(epp.getUsername())){
                BDHiringApplicantProfile.name.setText(String.valueOf(epp.getName()));
                BDHiringApplicantProfile.age.setText(String.valueOf(epp.getAge()));
                BDHiringApplicantProfile.gender.setSelectedItem(String.valueOf(epp.getGender()));
                BDHiringApplicantProfile.usertype.setSelectedItem(String.valueOf(epp.getUsertype()));
                BDHiringApplicantProfile.id.setText(String.valueOf(epp.getId()));
                BDHiringApplicantProfile.emailid.setText(String.valueOf(epp.getEmailid()));
                BDHiringApplicantProfile.bloodcentre.setText(String.valueOf(epp.getCentre()));
                BDHiringApplicantProfile.contact.setText(String.valueOf(epp.getContact()));
                BDHiringApplicantProfile.date.setText(String.valueOf(epp.getDate()));
                BDHiringApplicantProfile.qualification.setText(String.valueOf(epp.getQualification()));
                BDHiringApplicantProfile.username.setText(String.valueOf(epp.getUsername()));
                BDHiringApplicantProfile.password.setText(String.valueOf(epp.getPassword()));
                
//                BDDonorSlotPanel.username.setText(String.valueOf(selectedep.getUsername()));
               
               }}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        BDHiringAcceptedApplications sapframe = new BDHiringAcceptedApplications(s);
        BDApplicantSplit.setRightComponent(sapframe);   
        String user = display1.getText();
        BDHiringAcceptedApplications.username.setText(display1.getText());
        DefaultTableModel model = (DefaultTableModel) BDHiringAcceptedApplications.tableaccept.getModel();
        model.setRowCount(0);
        
        for (Accept ep:s.getAcceptdirectory().getAccept()){
                                                     
            if(user.equals(ep.getUsername()))
            {            
                Object[] row = new Object[4];
                row[0] = ep;
                row[1] = ep.getCentre();
                row[2] = ep.getId();
                row[3] = ep.getDate();                  
                       
                model.addRow(row);
            }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        MainLogin sapframe = new MainLogin(s);
        sapframe.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_homeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        BDHiringRejectedApplications sapframe = new BDHiringRejectedApplications(s);
        BDApplicantSplit.setRightComponent(sapframe);   
        String user = display1.getText();
        BDHiringRejectedApplications.username.setText(display1.getText());
        DefaultTableModel model = (DefaultTableModel) BDHiringRejectedApplications.tableaccept.getModel();
        model.setRowCount(0);
        
        for (Reject ep:s.getRejectdirectory().getReject()){
                                                     
            if(user.equals(ep.getUsername()))
            {            
                Object[] row = new Object[4];
                row[0] = ep;
                row[1] = ep.getCentre();
                row[2] = ep.getId();
                row[3] = ep.getDate();                  
                       
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BDHiringApplicantPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BDHiringApplicantPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BDHiringApplicantPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BDHiringApplicantPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new BDHiringApplicantPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane BDApplicantSplit;
    public static javax.swing.JLabel display;
    public static javax.swing.JLabel display1;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
